### ISSUE TITLE
CONFIG ENV

### ISSUE THREAD

**Issue by woooferz** [woooferz/skarf#27]
Add an environment variable called `CONFIG_JSON` and allow that to be a way to provide configuration to skarf. (With highest priority as how the config loader works it probably has to be.

**Comment by Xstar97** [comment]
You can probably set another variable as a boolean to make your life easier.
```
USE_CONFIG_FILE: false
```
 If it's false the "CONFIG_JSON" variable is required if true, check the /config for a config file.

**Comment by woooferz** [comment]
probably a good idea
