### ISSUE TITLE
RELME Support

### ISSUE THREAD

**Issue by egooner** [woooferz/skarf#41]
It would be useful to support rel="me" attributes within the <a> tag for things like verification of users on Mastodon.

I took a look at your code and created myself a new template version to try it out and it looks fairly trivial. I just added a relme=true to the links specific link config and updated the template. Hoping you can add something similar to the code.

```
{% if link['relme'] == True %}
rel="me"
{% endif %}
```

**Comment by woooferz** [comment]
added in 0.3 dev
